# 应用服务 WEB 访问端口
server.port=8081
bot.credential.path=creds.json
bot.api.baseurl=https://ilinkai.weixin.qq.com
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
